language: scala
jdk:
- oraclejdk8
scala:
- 2.10.5
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_install:
- git config --global user.email "aure.vandel@gmail.com"
- git config --global user.name "avandel"
- git remote set-url origin git@github.com:saagie/sbt-saagie-plugin.git
- openssl aes-256-cbc -K $encrypted_5cb87ecf328b_key -iv $encrypted_5cb87ecf328b_iv -in secrets.tar.enc -out secrets.tar
- ls
- tar xvf secrets.tar
- mv -fv id_rsa ~/.ssh/id_rsa
- mv -fv config ~/.ssh/config
- gpg --import secring.asc
script:
- git checkout develop
- sbt clean 'release with-defaults'
env:
  global:
  - secure: pakBsvceabARgfv6+9M15f9CmUDHBYzxJzg0ZyU2O4tC72dsAmwO4rQFMZ9s/twcqhI060P0ngUvSeFJJ3x/jY+YaS6WPx+GAGbIjw7nF+Y6QW9dkkBIwyXUmo0/KHl6wzRbly16kMu+ksfk2JSuf8FfuqRhQLoI7ydgfWE4LjbT9rKB2cqSW2oq7S8u5Q7HFRmyKU+g5Iewsew4jyChX2rswQGtZ3kIOrWQpkUq/i1VHQl200QlJJJC77eVks+QHj3RTnBBtTdgPzmfgyIN7LPXlUtNJuvP0X6l1xIJ7JG+IPdOi88Lnc3KgBwMWRNyFhBSGUR7+8go1P5JDb184YvO95QFefv9WHNc6rsaC5sQUevrfpdHCWOo1eQveFCEOtBhjg9ApY7KAvJIUZnarFz/BVh0Bb2YdPoXqc9VYGJWyl5JRTBDL0+vHqDaF0Vbh+HYffPu43HzPjHcN7N4jwpfRBM/1Lo5HvPZPdD3pxTAh8qTxvlNWy5JbjvASJI4gHvbBs6v26Wwp/zQTFZNc5UZOsnZ1jDVOFw7MK3IikRZXUNALSCCp3q7lnC9WNO50tI4HPd/Lfxy3Us02GkBzt5f+zp5Ewe5IURR48mH+WnTeXzHOLwuIv14OA3H0k5Wz1tebb+GxTgrbbEFMsnV5ezgVwzGqV0h4RzKtmZA5DA=
  - secure: xbKNtVtzKz6tyeYABE11cIq+WfJDmhzUwwon8zs3oBZkMvjcMG8QEDy1YDGFYtagBnQjAHwbhxM5yTq9bbQQZ7jy2u3+Q5RncXB6MNMg0ffNPJdNSr+wDZFvnC84zOTs08bw6SG+p1Pb84ZVghHiLGVjxAujncqq85UChcpifvH409uPOSBDHJ6KkXQUeBfdb9z7bPN7k+TcQI4v/ZZ9H3wYTtq6wrooBiTHHt/QSPfGfhxugLPiMWiSVILIssZvsCq42K5v0E4/prfJbv187Oxt9bGBcOfmF2MnElF7FE4n3Im7XmTXjtI9XoV0ZjAe/lH7Sw8stWI6jn1csr0Ovizicg14kQOrjPB7WX3DCHUYxOHrBrEPMFIekeCgK8UvnDJP8y7D9zeLIi7s0osEDEXcYO27NzUSqLwWlUGpW1j9K8zVHGLcHN+PbvxE8sqFTRmpdZqPrVlUtCPCixf4MYTTLfa2+iTfOW8XEJLLcOy2K8giZW1YDG9zXEIYgO6n8Uk+1wtVfchdM/e7rjWP2ohEFpwf0QjqHaXb1QEXiJsJ2QEOxSV6iyBCuGNnyATQsEyt3S7rGlMSuL+/CF1dsfcx8k8kzsghfZ5Wa1ez9ZWjAx7djS5ILlTAaY5FgmFnvsJmmT8S1VeUDYPY4nqThGDjyfV9CjhOu5/rKbyErUE=
  - secure: o9mJxTjc6MR03t1/FnJ46xGH4WO2pj/Lj20RUj25+pp1wWaBsyFlU3B/80XV043yvMLlhPLckehukQt7s9HlMEAbFBosPZtmaDOD2fc7XFRqH6MfpGLFHhZrvYydAVZEr766g4QBn0XwVVn2VepozHKTl2YnRlBfHRuoF7rgjOmj8yo7B4uCAIBn6oPQFt2WxzRZv/le+ClO0BtjHfIafx1IFhS61ZiqzStOsaACGsDd29JebHWbDXomTOG/YQKFU+0bzioYE+qjkKLkQSdpRjbsgLcBCEEBZh/YPopScXs4/lsEZpZmgWbr5AXxOehTqG21Hv9d3J0r0wmkNUwp8DacB8UsedZ8fInPOf82gL0T2jLHyy4vPhE/XkuGgTLP0rSKVTNcrPVsPJ/1beiwQcTVfM3bvZ0KrMTGQJtSAPv2+6CW7/HtJsZ6xAEHAGmnZXYky9SWjP5XlzU1zjraoZSfRCKBsChj1Vem4v//9zW6fYaH90IxjJUqYnK39irHummIpugfxTLr105kjmzmMwj0vx95fy/2J1P3sYrLuVloeBh46YTV14ri/EZgE+0cOqVHo7RQS3ozl5YyqRth+NNNVHq9rjZWpB9uktgAUN/tLUi9a2wYaRgwUlT6CNoFGTuLY+5wJvOiua2pKzBni5RHtLJzubAbRnFMwvu9y8A=
dd:
- openssl aes-256-cbc -K $encrypted_5cb87ecf328b_key -iv $encrypted_5cb87ecf328b_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
