language: scala
jdk:
- oraclejdk8
scala:
- 2.10.5
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
script:
- git checkout develop
- sbt clean 'release with-defaults'
env:
  global:
  - secure: pakBsvceabARgfv6+9M15f9CmUDHBYzxJzg0ZyU2O4tC72dsAmwO4rQFMZ9s/twcqhI060P0ngUvSeFJJ3x/jY+YaS6WPx+GAGbIjw7nF+Y6QW9dkkBIwyXUmo0/KHl6wzRbly16kMu+ksfk2JSuf8FfuqRhQLoI7ydgfWE4LjbT9rKB2cqSW2oq7S8u5Q7HFRmyKU+g5Iewsew4jyChX2rswQGtZ3kIOrWQpkUq/i1VHQl200QlJJJC77eVks+QHj3RTnBBtTdgPzmfgyIN7LPXlUtNJuvP0X6l1xIJ7JG+IPdOi88Lnc3KgBwMWRNyFhBSGUR7+8go1P5JDb184YvO95QFefv9WHNc6rsaC5sQUevrfpdHCWOo1eQveFCEOtBhjg9ApY7KAvJIUZnarFz/BVh0Bb2YdPoXqc9VYGJWyl5JRTBDL0+vHqDaF0Vbh+HYffPu43HzPjHcN7N4jwpfRBM/1Lo5HvPZPdD3pxTAh8qTxvlNWy5JbjvASJI4gHvbBs6v26Wwp/zQTFZNc5UZOsnZ1jDVOFw7MK3IikRZXUNALSCCp3q7lnC9WNO50tI4HPd/Lfxy3Us02GkBzt5f+zp5Ewe5IURR48mH+WnTeXzHOLwuIv14OA3H0k5Wz1tebb+GxTgrbbEFMsnV5ezgVwzGqV0h4RzKtmZA5DA=
  - secure: xbKNtVtzKz6tyeYABE11cIq+WfJDmhzUwwon8zs3oBZkMvjcMG8QEDy1YDGFYtagBnQjAHwbhxM5yTq9bbQQZ7jy2u3+Q5RncXB6MNMg0ffNPJdNSr+wDZFvnC84zOTs08bw6SG+p1Pb84ZVghHiLGVjxAujncqq85UChcpifvH409uPOSBDHJ6KkXQUeBfdb9z7bPN7k+TcQI4v/ZZ9H3wYTtq6wrooBiTHHt/QSPfGfhxugLPiMWiSVILIssZvsCq42K5v0E4/prfJbv187Oxt9bGBcOfmF2MnElF7FE4n3Im7XmTXjtI9XoV0ZjAe/lH7Sw8stWI6jn1csr0Ovizicg14kQOrjPB7WX3DCHUYxOHrBrEPMFIekeCgK8UvnDJP8y7D9zeLIi7s0osEDEXcYO27NzUSqLwWlUGpW1j9K8zVHGLcHN+PbvxE8sqFTRmpdZqPrVlUtCPCixf4MYTTLfa2+iTfOW8XEJLLcOy2K8giZW1YDG9zXEIYgO6n8Uk+1wtVfchdM/e7rjWP2ohEFpwf0QjqHaXb1QEXiJsJ2QEOxSV6iyBCuGNnyATQsEyt3S7rGlMSuL+/CF1dsfcx8k8kzsghfZ5Wa1ez9ZWjAx7djS5ILlTAaY5FgmFnvsJmmT8S1VeUDYPY4nqThGDjyfV9CjhOu5/rKbyErUE=
  - secure: tsaX6vp2Vax9LQckrv/QhzCg+Rbk9+HUfChVFqaKwO+NFscgA3bekrJtjJGo+ZyQCWY6ERWOmhr2C/MhILSEQWJLyTu3MCWCud4wjNe9lTuQAGrg601TK17FC+nBql31PR3g5TQ5zYxQ/RnEXojg8VD4Rm4S3qVZruMnPs+6J8AtscPjaFmoiL8f/tzSZNfgCCx+W8gbw96HLilrxYMczC0aVEHwHR3wNfHMI3MQQ/lwBAHmlyGGpa5GZxHvQ08qtmvq/GhOqvQaCJkoJqFefxJnaTCw++QObn3eIKkEnsQsVQ5gE9lUOIYcPU0Zj+PKY8RIq56B37WvztJzaHpR8uk7OXp/cLT16e+Fj7NaVR7/GG8zAwACWgRE/3v1t7egUDXIwCX7ZrM6Ft9fs1EfgR493h7suaTMRoqVAu7jvz0dPQQsNg7teVmK9xZowZv4ZjW6PEPh5Wlp3TeeoS7MsRH1muo8aTMIQ+ZQhYAexgMH9qj0TdC1BjLutkoYBVS9db50iPi6KK2R+Lg1cp8LUv6RBQK68DiQ7p417Uc9NzuN2PgoXx+LDxsK4oWsmuiep0LSkJDBfreL8MhcnwWpBrsWBhDBbqSV3FBpzocqbzNBIYc2RLaCkDOr9e3UmZqgDA9BRV+aS9Ku/dfZNRr6zmxRQgFBkRBwgUvRs/UARI4=
dd:
- openssl aes-256-cbc -K $encrypted_5cb87ecf328b_key -iv $encrypted_5cb87ecf328b_iv
  -in secring.gpg.enc -out ~\/.gnupg/secring.gpg -d
- openssl aes-256-cbc -K $encrypted_5cb87ecf328b_key -iv $encrypted_5cb87ecf328b_iv
  -in pubring.gpg.enc -out ~\/.gnupg/pubring.gpg -d
