language: scala
jdk:
  - oraclejdk7
scala:
  - 2.11.8
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
script:
  - sbt clean 'release with-defaults'
